import {
  BadgeCheck,
  BadgePercent,
  Banknote,
  BatteryCharging,
  Boxes,
  Briefcase,
  Building2,
  CalendarDays,
  ClipboardList,
  Coffee,
  CookingPot,
  Fan,
  Gift,
  HardHat,
  Headphones,
  HeartHandshake,
  House,
  Landmark,
  type LucideIcon,
  Megaphone,
  NotebookPen,
  Palette,
  Pen,
  PenTool,
  Pill,
  Search,
  ShieldCheck,
  Shirt,
  Ship,
  SlidersHorizontal,
  Smartphone,
  Speaker,
  Stethoscope,
  TreePine,
  Truck,
  Wallet,
  Warehouse,
  Watch,
} from 'lucide-react'

export const iconRegistry = {
  'badge-check': BadgeCheck,
  banknote: Banknote,
  boxes: Boxes,
  briefcase: Briefcase,
  building: Building2,
  calendar: CalendarDays,
  clipboard: ClipboardList,
  'cooking-pot': CookingPot,
  delivery: Truck,
  'desk-set': Pen,
  earbuds: Headphones,
  fan: Fan,
  flask: Coffee,
  gift: Gift,
  handshake: HeartHandshake,
  'hard-hat': HardHat,
  house: House,
  landmark: Landmark,
  megaphone: Megaphone,
  palette: Palette,
  'pen-set': PenTool,
  pill: Pill,
  'power-bank': BatteryCharging,
  pricing: BadgePercent,
  search: Search,
  shield: ShieldCheck,
  ship: Ship,
  shirt: Shirt,
  sliders: SlidersHorizontal,
  smartphone: Smartphone,
  speaker: Speaker,
  stationery: NotebookPen,
  stethoscope: Stethoscope,
  wallet: Wallet,
  warehouse: Warehouse,
  watch: Watch,
  wood: TreePine,
} as const satisfies Record<string, LucideIcon>

export type IconName = keyof typeof iconRegistry
